---
deployment:
  tasks:
    # 1. Tentukan folder target
    - export DEPLOYPATH_CORE=/home/shoa3397/ms_pos/
    - export DEPLOYPATH_PUBLIC=/home/shoa3397/public_html/public_pos/

    # 2. Buat direktori target jika belum ada
    - /bin/mkdir -p $DEPLOYPATH_CORE
    - /bin/mkdir -p $DEPLOYPATH_PUBLIC

    # 3. Salin file core aplikasi (kecuali .git dan folder public) ke ms_pos
    - /bin/rsync -rav --exclude='.git' --exclude='public' * $DEPLOYPATH_CORE

    # 4. Salin isi folder public/ ke public_html/public_pos
    - /bin/rsync -rav public/ $DEPLOYPATH_PUBLIC