services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sistem_manajemen_toko
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - appstorage:/var/www/storage
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  queue_worker:
    image: sistem_manajemen_toko
    container_name: queue_worker
    restart: unless-stopped
    command: php artisan queue:work
    depends_on:
      - app
      - redis
    volumes:
      - appstorage:/var/www/storage
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redisdata:
    driver: local
  appstorage:
    driver: local